### ISSUE TITLE
Parse metadata

### ISSUE THREAD

**Issue by Parnswir** [Killerameise/MMDS-Amazon-Reviews#1]
Info about the products should be useful for finding insights. There is sample data available at http://jmcauley.ucsd.edu/data/amazon/

**Comment by Killerameise** [comment]
Do you mean the Metadata?

**Comment by Aggharta** [comment]
The sample is only availabe when contacting the owner julian.mcauley@gmail.com.
Mail proposal:

> Dear Mr. McAuley,
> we are a student team from the Hasso Plattner Institute of the University of Potsdam, Germany. For our seminar "Mining Massive Datasets" we would like to use the Amazon Review Data from your website in order to evaluate which features make a product successful. We would appreciate if you could provide us the link to the sample data.
> Kind regards,

**Comment by Parnswir** [comment]
Yes, I meant the metadata. But you're right, let's write him an email. However, metadata parsing can be implemented without the data, using the sample on the website (as done with the review model).

**Comment by Killerameise** [comment]
It is implemented. But i don't know if it is working correctly.  Maybe i miss some attributes from salesRank. But the sample doesn't provide much information...

"salesRank":{  
      "Toys & Games":211836
   }

**Comment by Parnswir** [comment]
Why is SalesRank a class? Correct me if I'm wrong, but isn't this a dictionary (`Map<String, Integer>` in Java)?
